# Use an official Node.js runtime as a base image
FROM node:16

# Set the working directory in the container
WORKDIR /app

# Copy package files separately to leverage Docker caching
COPY frontend/package.json frontend/package-lock.json ./
RUN npm install && npm install cross-env --save-dev

# Copy the entire frontend code
COPY frontend/ .

# Expose the frontend port
EXPOSE 3000

# Build for production
RUN npm run build

# Serve the React app
CMD ["npm", "start"]
