# Use an official Node.js runtime as the base image
FROM node:16

# Set the working directory in the container
WORKDIR /app

# Copy the frontend dependencies
COPY frontend/package.json frontend/package-lock.json /app/

# Install dependencies
RUN npm install

# Copy the frontend source code
COPY frontend/ /app

# Expose the React app port
EXPOSE 3000

# Run the frontend app
CMD ["npm", "start"]
